image: node:lts

# Cache node_modules to speed up builds
cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public/*
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - main
